### ISSUE TITLE
Bug in Help page rendering

### ISSUE THREAD

**Issue by securonomics** [cx-candidates/OLD-pbx-candidate-answers#3]
Markdown in the .md file for the Help page is not rendering with any formatting. It appears to be because whatever is in the Help file is stripped and the entire file is treated as a list element.

Putting the following in the `contact-pbs-gs.md` file:
```
## E-mail
Please use [project-cx@photobox.com](mailto:project-cx@photobox.com)

## Slack
You should have received an invite to our Slack Organisation
```

appears as:
```
E-mail Please use project-cx@photobox.com Slack You should have received an invite to our Slack Organisation
```

and is rendered as:
```
<div class="list__excerpt">
E-mail Please use project-cx@photobox.com
Slack You should have received an invite to our Slack Organisation
</div>
```

A hack would be to include a separate file for each paragraph that needs a heading, but that seems a bit messy.

**Comment by securonomics** [comment]
Hey Dinis, 
I just wanted to see if you had an idea on this, since I'm putting the workflow document in the help section and I think the formatting is going to be odd.

**Comment by RandomFractals** [comment]
can you assign it to me for review?

**Comment by securonomics** [comment]
OK, so this is less of a bug and more of a formatting problem. The basic behavior is this:
- _index.md file pulls text from any file in the Help folder and displays a snippet,
- that snippet removes all formatting

This is fine for a longer file -- even though it looks messy -- but for shorter files, it just appears that that the file's formatting is gone. Current Help page has both a short file and a long file for comparison.
